import tags from './tags'

// this is a stack of news, the first here it'll be the first in the page
export default [
    // {
    //     title: "A política do incentivo",
    //     subtitle: "A política do incentivo define nossa sociedade",
    //     date: new Date('2023-02-22'),
    //     tags: [tags.POLITICA, tags.GEOPOLITICA, tags.LIBERALISMO],
    //     image: "teste.jpeg",
    //     link: "politica-incentivo",
    //     component: () => import('./posts/PoliticaIncentivo.vue'),
    // },
    // {
    //     title: "Refutando Ciro Gomes: O que eu concordo e o que discordo dele",
    //     subtitle: "-",
    //     date: new Date('2023-02-22'),
    //     tags: [tags.POLITICA, tags.GEOPOLITICA, tags.LIBERALISMO],
    //     image: "teste.jpeg",
    //     link: "refutando-ciro-gomes",
    //     component: () => import('./posts/PoliticaIncentivo.vue'),
    // },
    // {
    //     title: "Refutando xxxxxx: O que eu concordo e o que discordo dele",
    //     subtitle: "-",
    //     date: new Date('2023-02-22'),
    //     tags: [tags.POLITICA, tags.GEOPOLITICA, tags.LIBERALISMO],
    //     image: "teste.jpeg",
    //     link: "refutando-xxxxxxx1",
    //     component: () => import('./posts/PoliticaIncentivo.vue'),
    // },
    // {
    //     title: "Refutando xxxxxx: O que eu concordo e o que discordo dele",
    //     subtitle: "-",
    //     date: new Date('2023-02-22'),
    //     tags: [tags.POLITICA, tags.GEOPOLITICA, tags.LIBERALISMO],
    //     image: "teste.jpeg",
    //     link: "refutando-xxxxxxx2",
    //     component: () => import('./posts/PoliticaIncentivo.vue'),
    // },
    // {
    //     title: "Por que eu não como carne? Minha visão de mundo.",
    //     date: new Date('2023-02-26'),
    //     tags: [tags.OPINIAO, tags.FILOSOFIA],
    //     image: "teste.jpeg",
    //     link: "vegetariano",
    //     component: () => import('./posts/Vegetariano.vue'),
    // },
    // {
    //     title: "Cuba",
    //     subtitle: "Minha visão sobre esta ilha",
    //     date: new Date('2023-02-26'),
    //     tags: [tags.POLITICA, tags.OPINIAO, tags.GEOPOLITICA],
    //     image: "teste.jpeg",
    //     link: "cuba",
    //     component: () => import('./posts/Cuba.vue'),
    // },
    // {
    //     title: "Por que a esquerda gosta de chamar qualquer um que pense diferente de fascista?",
    //     date: new Date('2023-02-26'),
    //     tags: [tags.POLITICA],
    //     image: "teste.jpeg",
    //     link: "esquerda-gosta-de-chamar-fascista",
    //     component: () => import('./posts/EsquerdaGostaChamarFascista.vue'),
    // },
    // {
    //     title: "Minha geração está perdida",
    //     date: new Date('2023-02-26'),
    //     tags: [tags.OPINIAO],
    //     image: "minha-geracao-esta-perdida.jpg",
    //     link: "minha-geracao-esta-perdida",
    //     component: () => import('./posts/MinhaGeracaoEstaPerdida.vue'),
    // },
    // {
    //     title: "Como identificar uma teoria da conspiração",
    //     date: new Date('2023-02-26'),
    //     tags: [tags.POLITICA],
    //     image: "Dollarnote_siegel_hq.jpg",
    //     link: "como-identificar-uma-teoria-da-conspiracao",
    //     component: () => import('./posts/IdentificarConspiracao.vue'),
    // },
    // {
    //     title: "Por que você não deve temer IAs?",
    //     subtitle: "Uma breve explicação do que são IAs",
    //     date: new Date('2023-07-25'),
    //     tags: [tags.OPINIAO],
    //     image: "capa-pc.jpg",
    //     link: "temer-ias",
    //     component: () => import('./posts/PorqueNaoTemerIA.vue'),
    // },
    {
        title: "Devo fazer faculdade?",
        subtitle: "É muito comum este questionamento nos dias atuais",
        date: new Date('2023-08-26'),
        tags: [tags.OPINIAO],
        image: "faculdade.jpg",
        link: "faculdade",
        component: () => import('./posts/Faculdade.vue'),
    },
    {
        title: "Minha ideia com o blog",
        subtitle: "O motivo pela qual eu resolvi escrever minhas ideias",
        date: new Date('2023-07-23'),
        tags: [tags.OPINIAO],
        image: "capa-pc.jpg",
        link: "primeiro-post",
        component: () => import('./posts/PrimeiroPost.vue'),
    },
]
